import { randomUUID } from "crypto";

import {
  ClinicalQuestion,
  ClinicalEvidenceReference,
  QuestionCategory,
  QuestionEvaluationResult,
  QuestionGenerationContext,
  QuestionPriority,
  QuestionRule,
  QuestionSeverity,
  QuestionSource,
  TargetAudience,
} from "./QuestionTypes";

import {
  QuestionCreateRequest,
  QuestionEvaluationRequest,
} from "./QuestionModels";

import { QuestionHelper, QuestionContextHelper } from "./QuestionHelper";
import {
  QuestionRuleValidator,
  QuestionValidator,
} from "./QuestionValidator";

export class QuestionBuilder {
  public build(
    request: QuestionCreateRequest
  ): ClinicalQuestion {
    const validation = QuestionValidator.validateCreate(request);

    if (!validation.valid) {
      throw new Error(validation.errors.join(" "));
    }

    return QuestionHelper.createQuestion(
      randomUUID(),
      request
    );
  }

  public buildEvaluation(
    request: QuestionEvaluationRequest
  ): QuestionEvaluationResult {
    const contextValidation =
      QuestionValidator.validateContext(request.context);

    if (!contextValidation.valid) {
      throw new Error(contextValidation.errors.join(" "));
    }

    const questions = this.generateQuestions(
      request.context,
      request.rules
    );

    return Object.freeze({
      shouldAsk: questions.length > 0,
      confidence:
        QuestionContextHelper.calculateAverageConfidence(
          questions
        ),
      questions,
      generatedAt: new Date().toISOString(),
      reasoning: Object.freeze(
        this.buildReasoning(request.context, questions)
      ),
    });
  }

  private generateQuestions(
    context: QuestionGenerationContext,
    rules: readonly QuestionRule[]
  ): ClinicalQuestion[] {
    const generated: ClinicalQuestion[] = [];

    for (const rule of rules) {
      if (!rule.enabled) {
        continue;
      }

      const matched =
        QuestionRuleValidator.evaluateConditions(
          rule.conditions,
          this.createRuleContext(context)
        );

      if (!matched) {
        continue;
      }

      generated.push(
        this.createQuestionFromRule(context, rule)
      );
    }

    return QuestionContextHelper.deduplicateQuestions(
      QuestionHelper.sortByPriority(generated)
    );
  }

  private createQuestionFromRule(
    context: QuestionGenerationContext,
    rule: QuestionRule
  ): ClinicalQuestion {
    return this.build({
      patientId: context.patientId,

      category: rule.category,
      priority: rule.priority,
      severity: this.defaultSeverity(rule.category),

      title: this.defaultTitle(rule.category),
      question: this.defaultQuestion(rule.category),
      clinicalReason:
        rule.description ??
        "Generated by Clinical Question Engine.",

      responseType:
        QuestionContextHelper.inferResponseType(
          rule.category
        ),

      options:
        QuestionContextHelper.inferResponseType(
          rule.category
        ) === "YES_NO"
          ? QuestionContextHelper.createBooleanOptions()
          : undefined,

      target:
        QuestionContextHelper.inferTargetAudience(
          rule.category
        ),

      consultationMode: context.consultationMode,

      evidence: context.evidence,

      triggers: [
        {
          id: randomUUID(),
          trigger: context.trigger,
          source: "AI",
          description:
            "Generated from clinical evaluation.",
          createdAt: new Date().toISOString(),
        },
      ],

      timeline: context.timelineEventId
        ? {
            timelineId: context.timelineEventId,
            eventId: context.timelineEventId,
            eventType: context.trigger,
          }
        : undefined,

      treatment: context.consultationId
        ? {
            consultationId:
              context.consultationId,
            prescriptionId:
              context.prescriptionId,
          }
        : undefined,

      ruleId: rule.id,

      confidence: 0.9,
      source: "AI",
      tags: [rule.category],
    });
  }


  private createRuleContext(
    context: QuestionGenerationContext
  ): Record<string, unknown> {
    return {
      patientId: context.patientId,
      consultationId: context.consultationId,
      prescriptionId: context.prescriptionId,
      timelineEventId: context.timelineEventId,

      consultationMode: context.consultationMode,

      trigger: context.trigger,

      evidenceCount: context.evidence.length,
      comparisonCompleted: context.comparisonCompleted,
      treatmentAnalysed: context.treatmentAnalysed,
      timelineUpdated: context.timelineUpdated,
    };
  }

  private buildReasoning(
    context: QuestionGenerationContext,
    questions: readonly ClinicalQuestion[]
  ): string[] {
    const reasoning: string[] = [];

    reasoning.push(
      `Trigger detected: ${context.trigger}.`
    );

    if (context.timelineUpdated) {
      reasoning.push(
        "Timeline engine contributed clinical evidence."
      );
    }

    if (context.treatmentAnalysed) {
      reasoning.push(
        "Treatment engine completed analysis."
      );
    }

    if (context.comparisonCompleted) {
      reasoning.push(
        "Comparison engine detected clinically relevant changes."
      );
    }

    if (context.evidence.length > 0) {
      reasoning.push(
        `${context.evidence.length} clinical evidence item(s) evaluated.`
      );
    }

    if (questions.length === 0) {
      reasoning.push(
        "No follow-up questions were clinically indicated."
      );
    } else {
      reasoning.push(
        `${questions.length} follow-up question(s) generated.`
      );
    }

    return reasoning;
  }

  private defaultTitle(
    category: QuestionCategory
  ): string {
    switch (category) {
      case "MEDICATION_ADHERENCE":
        return "Medication Adherence";

      case "MEDICATION_TOLERANCE":
        return "Medication Tolerance";

      case "ADVERSE_EFFECT":
        return "Possible Side Effects";

      case "SYMPTOM_PROGRESSION":
        return "Symptom Progress";

      case "INVESTIGATION_FOLLOW_UP":
        return "Investigation Follow-up";

      case "EMERGENCY_ESCALATION":
        return "Urgent Clinical Review";

      default:
        return "Clinical Clarification";
    }
  }

  private defaultQuestion(
    category: QuestionCategory
  ): string {
    switch (category) {
      case "MEDICATION_ADHERENCE":
        return "Have you been taking your medicines exactly as prescribed?";

      case "MEDICATION_TOLERANCE":
        return "Are you tolerating your current medications well?";

      case "ADVERSE_EFFECT":
        return "Have you experienced any new side effects after starting this medication?";

      case "SYMPTOM_PROGRESSION":
        return "Have your symptoms improved, worsened, or remained unchanged?";

      case "INVESTIGATION_FOLLOW_UP":
        return "Have you completed the investigations advised by your doctor?";

      case "FOLLOW_UP_REMINDER":
        return "Have you attended your scheduled follow-up consultation?";

      case "DIAGNOSIS_CLARIFICATION":
        return "Can you provide additional information about your diagnosis?";

      default:
        return "Could you provide additional clinical information?";
    }
  }

  private defaultSeverity(
    category: QuestionCategory
  ): QuestionSeverity {
    switch (category) {
      case "EMERGENCY_ESCALATION":
        return "LIFE_THREATENING";

      case "ADVERSE_EFFECT":
        return "MAJOR";

      case "MEDICATION_TOLERANCE":
      case "SYMPTOM_PROGRESSION":
        return "MODERATE";

      default:
        return "NONE";
    }
  }
}