import {
    PDFDocument,
    StandardFonts
} from "pdf-lib";

import { PdfTheme } from "./PdfTheme";
import { PdfHeader } from "./PdfHeader";
import { PdfDrawing } from "./PdfDrawing";

import {
    ExecutiveSummarySection,
    ExecutiveSummaryData
} from "./ExecutiveSummarySection";

import {
    TrendReportInfo
} from "./trendReportPdf";

export class ExecutiveSummaryPdf {

    async generate(
        data: ExecutiveSummaryData,
        report: TrendReportInfo = {}
    ): Promise<Uint8Array> {

        const pdf =
            await PDFDocument.create();

        const regularFont =
            await pdf.embedFont(
                StandardFonts.Helvetica
            );

        const boldFont =
            await pdf.embedFont(
                StandardFonts.HelveticaBold
            );

        const page =
            pdf.addPage([
                PdfTheme.page.width,
                PdfTheme.page.height
            ]);

        PdfHeader.draw({

            page,

            boldFont,

            regularFont,

            title: "Executive Health Summary",

            generatedOn: new Date(),

            patientName: report.patientName,

            age: report.age,

            sex: report.sex,

            doctorName: report.doctorName,

            hospitalName: report.hospitalName,

            reportPeriod: report.reportPeriod

        });

        ExecutiveSummarySection.draw({

            page,

            boldFont,

            regularFont,

            x: PdfTheme.page.margin,

            y:
                PdfTheme.page.height -
                PdfTheme.page.margin -
                PdfTheme.header.contentTopOffset,

            width:
                PdfTheme.page.contentWidth,

            data

        });

        PdfDrawing.divider(page, {

            x: PdfTheme.page.margin,

            y: 70,

            width:
                PdfTheme.page.contentWidth

        });

        PdfDrawing.multilineText(page, {

            text:
`Medical Disclaimer

This report is automatically generated from health information recorded by the patient or caregiver. It is intended to support health monitoring and should not replace professional medical advice, diagnosis or treatment.

Generated by CareVR

Designed & Developed by
Suraj Premnath

© 2026 CareVR. All Rights Reserved.`,

            x: PdfTheme.page.margin,

            y: 58,

            size: 9,

            font: regularFont

        }, 12);

        return await pdf.save();

    }

}

export const executiveSummaryPdf =
    new ExecutiveSummaryPdf();