import {
    PDFDocument,
    PDFFont,
    rgb
} from "pdf-lib";

import { PdfTheme } from "./PdfTheme";
import { PdfDrawing } from "./PdfDrawing";

export interface PdfFooterOptions {

    pdf: PDFDocument;

    regularFont: PDFFont;

}

export class PdfFooter {

    static draw(
        options: PdfFooterOptions
    ) {

const {
    pdf,
    regularFont
} = options;

const pages = pdf.getPages();

const left = PdfTheme.page.margin;

const width = PdfTheme.page.contentWidth;

pages.forEach((page, index) => {

    PdfDrawing.divider(page, {

        x: left,

        y: 72,

        width

    });

PdfDrawing.text(page, {

    text: "MEDICAL DISCLAIMER",

    x: left,

    y: 64,

    size: 8,

    font: regularFont,

    color: rgb(0.25, 0.25, 0.25)

});

const disclaimerTop = 60;

PdfDrawing.text(page, {

    text: "This report is automatically generated from health information recorded by the patient or caregiver.",

    x: left,

    y: 50,

    size: 7.5,

    font: regularFont

});

PdfDrawing.text(page, {

    text: "It is intended to support health monitoring and should not replace professional medical advice, diagnosis or treatment.",

    x: left,

    y: 38,

    size: 7.5,

    font: regularFont

});

PdfDrawing.text(page, {

    text: "Generated by CareVR",

    x: left,

    y: 2,

    size: 8,

    font: regularFont,

    color: rgb(0.15,0.15,0.15)

});

PdfDrawing.text(page, {

    text: "Designed & Developed by Suraj Premnath",

    x: 210,

    y: 2,

    size: 8,

    font: regularFont,

    color: rgb(0.15,0.15,0.15)

});

PdfDrawing.text(page, {

    text: "Confidential Clinical Report",

    x: left,

    y: 12,

    size: 8,

    font: regularFont,

    color: rgb(0.45, 0.45, 0.45)

});

PdfDrawing.text(page, {

    text: `Page ${index + 1} of ${pages.length}`,

    x: PdfTheme.page.width - 110,

    y: 10,

    size: 8,

    font: regularFont,

    color: rgb(0.45, 0.45, 0.45)

});

});

    }

}