import {
    PDFDocument,
    StandardFonts
} from "pdf-lib";

import { PdfTheme } from "./PdfTheme";
import { PdfHeader } from "./PdfHeader";
import { PdfDrawing } from "./PdfDrawing";
import {
    PdfSection,
    TrendMetric
} from "./PdfSection";

export interface TrendReportInfo {

    patientName?: string;

    age?: string;

    sex?: string;

    doctorName?: string;

    hospitalName?: string;

    reportPeriod?: string;

}

export class TrendReportPdf {

async generate(
    trends: TrendMetric[],
    report: TrendReportInfo = {}
): Promise<Uint8Array> {

        const pdf =
            await PDFDocument.create();

        const regularFont =
            await pdf.embedFont(
                StandardFonts.Helvetica
            );

        const boldFont =
            await pdf.embedFont(
                StandardFonts.HelveticaBold
            );

        let page =
            pdf.addPage([
                PdfTheme.page.width,
                PdfTheme.page.height
            ]);

PdfHeader.draw({

    page,

    boldFont,

    regularFont,

    generatedOn: new Date(),

    patientName: report.patientName,

    age: report.age,

    sex: report.sex,

    doctorName: report.doctorName,

    hospitalName: report.hospitalName,

    reportPeriod: report.reportPeriod

});

let currentY =
    PdfTheme.page.height -
    PdfTheme.page.margin -
    PdfTheme.header.contentTopOffset;

        const left =
            PdfTheme.page.margin;

        const width =
            PdfTheme.page.contentWidth;

        for (const trend of trends) {

            if (
                currentY <
                PdfTheme.header.pageBreakMargin
            ) {

                page =
                    pdf.addPage([
                        PdfTheme.page.width,
                        PdfTheme.page.height
                    ]);

                PdfHeader.draw({

    page,

    boldFont,

    regularFont,

    generatedOn: new Date(),

    patientName: report.patientName,

    age: report.age,

    sex: report.sex,

    doctorName: report.doctorName,

    hospitalName: report.hospitalName,

    reportPeriod: report.reportPeriod

});

                currentY =
    PdfTheme.page.height -
    PdfTheme.page.margin -
    PdfTheme.header.contentTopOffset;

            }

            currentY =
                PdfSection.drawSection({

                    page,

                    boldFont,

                    regularFont,

                    trend,

                    x: left,

                    y: currentY,

                    width

                });

        }

PdfDrawing.divider(page,{
    x:PdfTheme.page.margin,
    y:70,
    width:PdfTheme.page.contentWidth
});

PdfDrawing.multilineText(page,{
    text:
`Medical Disclaimer: This report is automatically generated from health information recorded by the patient or caregiver. 
It is intended to support 
health monitoring and should not replace professional medical advice, diagnosis or treatment.

Generated by CareVR | Designed & Developed by Suraj Premnath | © 2026 CareVR. All Rights Reserved.`,
    x:PdfTheme.page.margin,
    y:58,
    size:9,
    font:regularFont
},12);

return await pdf.save();

    }

}

export const trendReportPdf =
    new TrendReportPdf();