"use client";

interface Props {
    generatedAt: string;
    version: string;
    generatedBy: string;
}

function formatDate(value: string) {
    return new Date(value).toLocaleString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
}

export function Footer({
    generatedAt,
    version,
    generatedBy,
}: Props) {

    return (

        <footer className="rounded-3xl border border-slate-200 bg-white shadow-sm">

            <div className="flex flex-col gap-6 px-8 py-6 lg:flex-row lg:items-center lg:justify-between">

                <div>

                    <h3 className="text-lg font-semibold text-slate-900">
                        CareVR Health Timeline
                    </h3>

                    <p className="mt-2 text-sm text-slate-500">
                        Automatically generated longitudinal patient journey from
                        consultations, assessments and daily care records.
                    </p>

                </div>

                <div className="grid gap-2 text-sm text-slate-600 lg:text-right">

                    <div>
                        <span className="font-medium text-slate-900">
                            Generated
                        </span>{" "}
                        {formatDate(generatedAt)}
                    </div>

                    <div>
                        <span className="font-medium text-slate-900">
                            Version
                        </span>{" "}
                        {version}
                    </div>

                    <div>
                        <span className="font-medium text-slate-900">
                            Generated By
                        </span>{" "}
                        {generatedBy}
                    </div>

                </div>

            </div>

        </footer>

    );

}