import fs from "node:fs";
import path from "node:path";
import { DecisionResult } from "./decisionEngine";

export interface CanonicalOptions {
  outputDir?: string;
  fileName?: string;
}

export function updateCanonical(
  decisions: DecisionResult[],
  options: CanonicalOptions = {}
) {
  const outputDir = options.outputDir ?? "reports";
  const fileName = options.fileName ?? "JourneyCanonical.md";

  fs.mkdirSync(outputDir, { recursive: true });

  const markdown = buildCanonical(decisions);

  fs.writeFileSync(
    path.join(outputDir, fileName),
    markdown,
    "utf8"
  );
}

function buildCanonical(
  decisions: DecisionResult[]
): string {
  const lines: string[] = [];

  lines.push("# Journey Canonical");
  lines.push("");
  lines.push(
    "> Auto-generated by Journey Audit. Do not edit manually."
  );
  lines.push("");

  const grouped = group(decisions);

  for (const [decision, items] of grouped) {
    lines.push(`## ${decision}`);
    lines.push("");

    for (const item of sort(items)) {
      lines.push(`### ${item.symbol}`);
      lines.push("");

      lines.push(`**Kind**: ${item.kind}`);
      lines.push("");

      lines.push(`**Decision**: ${item.decision}`);
      lines.push("");

      lines.push(`**Confidence**: ${item.confidence}%`);
      lines.push("");

      if (item.canonical) {
        lines.push(
          `**Canonical File**: \`${normalize(item.canonical)}\``
        );
        lines.push("");
      }

      lines.push(`**Reason**`);
      lines.push("");
      lines.push(item.reason);
      lines.push("");

      lines.push("**Occurrences**");
      lines.push("");

      for (const occurrence of [...item.occurrences].sort()) {
        const canonical =
          item.canonical &&
          normalize(occurrence) === normalize(item.canonical);

        lines.push(
          `- ${canonical ? "✅" : "-"} \`${normalize(
            occurrence
          )}\``
        );
      }

      lines.push("");
    }
  }

  return lines.join("\n");
}

function group(
  decisions: DecisionResult[]
): Map<string, DecisionResult[]> {
  const map = new Map<string, DecisionResult[]>();

  for (const decision of decisions) {
    if (!map.has(decision.decision)) {
      map.set(decision.decision, []);
    }

    map.get(decision.decision)!.push(decision);
  }

  return new Map(
    [...map.entries()].sort(([a], [b]) =>
      a.localeCompare(b)
    )
  );
}

function sort(
  items: DecisionResult[]
): DecisionResult[] {
  return [...items].sort((a, b) => {
    if (a.symbol !== b.symbol) {
      return a.symbol.localeCompare(b.symbol);
    }

    return b.confidence - a.confidence;
  });
}

function normalize(file: string) {
  return file.replace(/\\/g, "/");
}