export function expandMedicalText(text: string): string {
    return text

        .replace(/\bHTN\b/gi, "Hypertension")
        .replace(/\bDM\b/gi, "Diabetes Mellitus")
        .replace(/\bURTI\b/gi, "Upper Respiratory Tract Infection")
        .replace(/\bLRTI\b/gi, "Lower Respiratory Tract Infection")
        .replace(/\bBPH\b/gi, "Benign Prostatic Hyperplasia")
        .replace(/\bCRP\b/gi, "C-Reactive Protein")
        .replace(/\bCBC\b/gi, "Complete Blood Count")
        .replace(/\bESR\b/gi, "Erythrocyte Sedimentation Rate")
        .replace(/\bPSA\b/gi, "Prostate Specific Antigen")
        .replace(/\bUSG\b/gi, "Ultrasound")
        .replace(/\bUS\b/gi, "Ultrasound")
        .replace(/\bCT\b/gi, "CT Scan")
        .replace(/\bMRI\b/gi, "MRI Scan")
        .replace(/\bXR\b/gi, "X-Ray")
        .replace(/\bECG\b/gi, "Electrocardiogram")
        .replace(/\bEcho\b/gi, "Echocardiogram")
        .replace(/\bSpO2\b/gi, "Oxygen Saturation")
        .replace(/\bBP\b/gi, "Blood Pressure")
        .replace(/\bPR\b/gi, "Pulse Rate")
        .replace(/\bHR\b/gi, "Heart Rate")
        .replace(/\bVit\b/gi, "Vitamin")
        .replace(/\bVit D\b/gi, "Vitamin D")
        .replace(/\bVit B12\b/gi, "Vitamin B12")
        .replace(/\bB12\b/gi, "Vitamin B12")
        .replace(/\bCa\b/gi, "Calcium")
        .replace(/\bFe\b/gi, "Iron")
        .replace(/\bPO\b/gi, "By Mouth")
        .replace(/\bOD\b/gi, "Once Daily")
        .replace(/\bBD\b/gi, "Twice Daily")
        .replace(/\bTDS\b/gi, "Three Times Daily")
        .replace(/\bQID\b/gi, "Four Times Daily")
        .replace(/\bSOS\b/gi, "As Needed")
        .replace(/\bPRN\b/gi, "As Needed")
        .replace(/\bHS\b/gi, "At Bedtime")
        .replace(/\bAC\b/gi, "Before Food")
        .replace(/\bPC\b/gi, "After Food")
        .replace(/\bstatin\b/gi, "Statin Therapy")
        .replace(/\bAld\.?\s*supply\b/gi, "Alcohol Consumption")
        .replace(/\bmixed diet\b/gi, "Mixed Diet")
        .replace(/\bveg\b/gi, "Vegetarian");
}