/**
 * ------------------------------------------------------------
 * CAREVR
 * Auto Generated
 *
 * Entity : JourneyConfidence
 * Type   : Default
 *
 * Generated by scaffoldDomain.ts
 * ------------------------------------------------------------
 */

export {};
