// components/journey-review/JourneyActions.tsx

"use client";

import {
  CheckCircle2,
  ClipboardCheck,
  Download,
  FileText,
  Share2,
  ArrowRight,
  Save,
} from "lucide-react";

import {
  JourneyAction,
  JourneyActionType,
} from "@/lib/journey";

interface JourneyActionsProps {
  actions: JourneyAction[];

  onExecute?: (
    action: JourneyAction,
  ) => void;
}

export function JourneyActions({
  actions,
  onExecute,
}: JourneyActionsProps) {
  if (actions.length === 0) {
    return null;
  }

  return (
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">

      <div className="border-b border-slate-100 px-6 py-5">

        <div className="flex items-center gap-3">

          <div className="rounded-xl bg-emerald-100 p-3">
            <ClipboardCheck className="h-6 w-6 text-emerald-700" />
          </div>

          <div>

            <h3 className="text-xl font-bold text-slate-900">
              Recommended Actions
            </h3>

            <p className="mt-1 text-sm text-slate-500">
              Suggested next steps generated by CareVR.
            </p>

          </div>

        </div>

      </div>

      <div className="space-y-4 p-6">

        {actions.map(action => (
          <ActionCard
            key={action.id}
            action={action}
            onExecute={() =>
              onExecute?.(action)
            }
          />
        ))}

      </div>

    </div>
  );
}

interface ActionCardProps {
  action: JourneyAction;
  onExecute?: () => void;
}

function ActionCard({
  action,
  onExecute,
}: ActionCardProps) {
  const Icon = getIcon(action.type);

  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 p-5 transition hover:border-sky-300 hover:shadow-sm">

      <div className="flex flex-wrap items-start justify-between gap-4">

        <div className="flex flex-1 gap-4">

          <div className="rounded-xl bg-white p-3 shadow-sm">
            <Icon className="h-5 w-5 text-sky-600" />
          </div>

          <div>

            <h4 className="font-semibold text-slate-900">
              {action.title}
            </h4>

            <p className="mt-2 text-sm leading-6 text-slate-600">
              {action.description}
            </p>

            {action.priority && (
              <div className="mt-3">

                <span
                  className={`rounded-full px-3 py-1 text-xs font-semibold ${priorityClass(
                    action.priority,
                  )}`}
                >
                  {action.priority}
                </span>

              </div>
            )}

          </div>

        </div>

        <button
          type="button"
          onClick={onExecute}
          className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-sky-700"
        >
          Execute

          <ArrowRight className="h-4 w-4" />

        </button>

      </div>

    </div>
  );
}

function getIcon(type: JourneyActionType) {
  switch (type) {
    case JourneyActionType.SAVE:
      return Save;

    case JourneyActionType.EXPORT:
      return Download;

    case JourneyActionType.SHARE:
      return Share2;

    case JourneyActionType.GENERATE_REPORT:
      return FileText;

    default:
      return CheckCircle2;
  }
}

function priorityClass(priority: string) {
  switch (priority.toUpperCase()) {
    case "HIGH":
      return "bg-red-100 text-red-700";

    case "MEDIUM":
      return "bg-amber-100 text-amber-700";

    default:
      return "bg-green-100 text-green-700";
  }
}