import HelpBackButton from "@/Components/help/HelpBackButton";

export default function PrivacyPage() {
    return (
        <>
<HelpBackButton />
            <h2
                style={{
                    fontSize: "30px",
                    marginBottom: "24px",
                    color: "#111827",
                }}
            >
                🔒 Privacy & Security
            </h2>

            {/* Overview */}

            <section style={sectionStyle}>

                <h3 style={headingStyle}>
                    Your Privacy
                </h3>

                <p style={paragraphStyle}>
                    CareVR is designed with privacy and security in mind.
                    Your health information is intended to be accessible only to you and other authorized users of your account.
                </p>

            </section>


{/* Health Information */}

<section style={sectionStyle}>

    <h3 style={headingStyle}>
        Your Health Information
    </h3>

    <p style={paragraphStyle}>
        CareVR helps you organize the health information that you choose to
        record.
    </p>

    <p style={paragraphStyle}>
        Depending on how you use the application, this may include patient
        information, daily health observations, health assessments and
        reports generated within CareVR.
    </p>

    <p style={paragraphStyle}>
        This information is used only to help you monitor health, review
        trends and generate reports for discussions with your healthcare
        provider.
    </p>

</section>


            {/* Security */}

            <section style={sectionStyle}>

                <h3 style={headingStyle}>
                    Security
                </h3>

                <p style={paragraphStyle}>
                    CareVR uses authenticated user access to help protect
                    health information. Only signed-in users can access
                    their data and reports.
                </p>

            </section>

            {/* Sharing */}

            <section style={sectionStyle}>

                <h3 style={headingStyle}>
                    Sharing Information
                </h3>

                <p style={paragraphStyle}>
                    Reports generated by CareVR can be shared with doctors,
                    hospitals or caregivers whenever required. Always
                    review your report before sharing it.
                </p>

            </section>

            {/* Responsibility */}

            <section style={sectionStyle}>

                <h3 style={headingStyle}>
                    Your Responsibility
                </h3>

                <ul style={listStyle}>
                    <li>Keep your login credentials secure.</li>
                    <li>Verify information before saving.</li>
                    <li>Share reports only with trusted healthcare providers.</li>
                    <li>Sign out when using a shared device.</li>
                </ul>

            </section>

            {/* Disclaimer */}

            <section style={sectionStyle}>

                <h3 style={headingStyle}>
                    Important Disclaimer
                </h3>

                <p style={paragraphStyle}>
                    CareVR is designed to support health record keeping and
                    clinical discussions. It is not intended to diagnose,
                    treat or replace professional medical advice. Always
                    consult a qualified healthcare professional regarding
                    medical concerns.
                </p>

            </section>

        </>
    );
}

const sectionStyle: React.CSSProperties = {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "24px",
    marginBottom: "24px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
};

const headingStyle: React.CSSProperties = {
    marginTop: 0,
    marginBottom: "14px",
    color: "#111827",
    fontSize: "22px",
};

const paragraphStyle: React.CSSProperties = {
    color: "#4b5563",
    lineHeight: 1.8,
    marginBottom: 0,
};

const listStyle: React.CSSProperties = {
    color: "#4b5563",
    lineHeight: 2,
    paddingLeft: "24px",
    marginBottom: 0,
};