import {
  RecommendationView,
} from "./recommendationView";

/**
 * Presentation model for the Journey Review Treatment Decision card.
 */
export interface TreatmentDecisionView {
  /**
   * User-friendly treatment decision.
   */
  decision: string;

  /**
   * Current treating doctor.
   */
  activeDoctor?: string;

  /**
   * Current treating hospital.
   */
  activeHospital?: string;

  /**
   * Why this treatment decision was made.
   */
  reason?: string;

  /**
   * Clinical notes displayed to the reviewer.
   */
  notes?: string;

  /**
   * Recommendations generated by the engine.
   */
  recommendations: RecommendationView[];

  /**
   * Indicates whether the previous treatment has been archived.
   */
  archived: boolean;
}